services:
  - type: web
    name: supplyiq-api
    runtime: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: sladethedeciever@gmail.com
      - key: SMTP_PASS
        value: rxttzokleurmojti
      - key: SESSION_SECRET
        value: 2a3f339685ea4eac09a6100da64525de2f3b25635b9b824c2a84c7f34a7e8640
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: supplyiq-db
    plan: free
    region: frankfurt
    postgresMajorVersion: 16
